# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: Apache-2.0

stages:
  - build
  - test
  - deploy

.script-github_token: &script-github_token
  - git config --global --add url."https://$PAT_GITHUB@github".insteadOf https://github

wheel:
  stage: build
  extends: .wheel
  script:
    - *script-github_token
    - pip wheel . -w dist/

pages:
  stage: build
  extends: .pages
  variables:
    OUTPUT_DIR: public
    SPHINX_DEPENDENCIES: ".[docs]"
  only: [master]
  before_script:
    - *script-github_token

pages:test:
  extends: pages
  variables:
    OUTPUT_DIR: pages-test
  only: []
  except: [master]
  before_script:
    - *script-github_token

coverage:
  stage: test
  extends: .coverage
  variables:
    COVERAGE_SOURCE: capella2polarion
  needs: []
  before_script:
    - *script-github_token

pre-commit:
  stage: test
  extends: .pre-commit
  needs: []
  before_script:
    - *script-github_token

artifactory:
  stage: deploy
  extends: .artifactory
  needs:
    - job: wheel
      artifacts: true
    - job: coverage
    - job: pre-commit
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

include:
  - project: "se-toolchain/ci-templates-docker"
    ref: master
    file:
      - "/gitlab-ci/docker/upload-registry.yml"
      - "/gitlab-ci/generic/pre-commit.yml"
      - "/gitlab-ci/python/sphinx.yml"
      - "/gitlab-ci/python/test.yml"
      - "/gitlab-ci/python/wheel.yml"
