# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: Apache-2.0

stages:
  - build
  - test
  - deploy

.patch-pyproject-toml: &patch-pyproject-toml
  - sed -i -e 's/\(^  "polarion-rest-api-client\).*",/\1",/' pyproject.toml

wheel:
  stage: build
  extends: .wheel
  before_script:
    - *patch-pyproject-toml

pages:
  stage: build
  extends: .pages
  variables:
    OUTPUT_DIR: public
    SPHINX_DEPENDENCIES: ".[docs]"
  only: [main]
  before_script:
    - *patch-pyproject-toml

pages:test:
  extends: pages
  variables:
    OUTPUT_DIR: pages-test
  only: []
  except: [main]
  before_script:
    - *patch-pyproject-toml

coverage:
  stage: test
  extends: .coverage
  variables:
    COVERAGE_SOURCE: capella2polarion
  needs: []
  before_script:
    - *patch-pyproject-toml

pre-commit:
  stage: test
  extends: .pre-commit
  needs: []
  before_script:
    - *patch-pyproject-toml

artifactory:
  stage: deploy
  extends: .artifactory
  needs:
    - job: wheel
      artifacts: true
    - job: coverage
    - job: pre-commit
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - project: "se-toolchain/ci-templates-docker"
    ref: master
    file:
      - "/gitlab-ci/docker/upload-registry.yml"
      - "/gitlab-ci/generic/pre-commit.yml"
      - "/gitlab-ci/python/sphinx.yml"
      - "/gitlab-ci/python/test.yml"
      - "/gitlab-ci/python/wheel.yml"
