# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, pre-merge-commit]
minimum_pre_commit_version: 4.0.0
repos:
  - repo: https://github.com/gitleaks/gitleaks.git
    rev: v8.24.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: Insert Apache license headers (shell-style comments)
        files: '(?:^|/)(?:.*\.(?:py|sh|toml|ya?ml)|Dockerfile|Makefile)$'
        exclude: '(?:^|/)\..+|^docs/Makefile$'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '#'
      - id: insert-license
        name: Insert CC0 license headers (shell-style comments)
        files: '(?:^|/)(?:codeql-analysis.yml|dependabot.yml|\.(?:pre-commit-config.yaml|(?:git|helm|docker)ignore))$'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_cc0.txt
          - --comment-style
          - '#'
      - id: insert-license
        name: Insert license headers (XML-style comments)
        files: '\.(?:html|md|xml)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '<!--| ~| -->'
      - id: insert-license
        name: Insert Apache license headers (C-style comments)
        files: '\.(?:s?css|js|ts)$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '/*| *| */'
      - id: insert-license
        name: Insert Apache license headers (reST comments)
        files: '\.rst$'
        exclude: '(?:^|/)\..+'
        args:
          - --detect-license-in-X-top-lines=15
          - --license-filepath
          - LICENSES/.license_header_apache.txt
          - --comment-style
          - '..|  |'
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38 # Don't autoupdate until https://github.com/PyCQA/docformatter/issues/293 is fixed
    hooks:
      - id: docformatter
        additional_dependencies:
          - docformatter[tomli]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--extend-ignore=FIX, --fix]
      - id: ruff-format
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint-docker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - bidict
          - cairosvg
          - capellambse==0.6.6
          - click
          - jinja2
          - polarion-rest-api-client==1.2.0
          - pydantic
          - types-requests
          - types-PyYAML
        exclude: tests
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - '@commitlint/config-conventional'
