# Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Build

on:
  push:
    branches: ["*"]
    pull_request: [main]
    tags: ["v*.*.*"]

jobs:
  test:
    name: Test with Python ${{matrix.python_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python_version}}
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('pyproject.toml')}}
          restore-keys: |
            ${{runner.os}}-pip-
            ${{runner.os}}-
      - name: Upgrade Pip
        run: |-
          python -m pip install -U pip
      - name: Add git PAT
        run: |-
          git config --global --add url."https://${{ secrets.PAT_GITHUB }}@github".insteadOf https://github
      - name: Pre-install private Github dependencies
        run: |-
          python -m pip install git+https://github.com/DSD-DBS/polarion-rest-api-client.git@v0.4.0
      - name: Install test dependencies
        run: |-
          python -m pip install '.[test]'
      - name: Run unit tests
        run: |-
          python -m pytest --cov-report=term --cov=capella2polarion --rootdir=.

  build:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: pyproject.toml
          python-version: "3.12"
      - name: Install dependencies
        run: python -m pip install -U pip build twine
      - name: Build packages
        run: python -m build
      - name: Verify packages
        run: python -m twine check dist/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    environment:
      name: pypi
      url: https://pypi.org/project/capella-polarion
    permissions:
      id-token: write
    steps:
      - name: Download built wheel
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
